[gcp_service_account]
type = "service_account"
project_id = "terminal-files"
private_key_id = "0a5992dd1864f04588354c12394a86bc125d40fc"
private_key = '''
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC93eOrLzLSstxH
PaLTNNen0GmQFXaNBGTFRVr9ytUBD2S3tIqT4F/x67wwt/z5SXhq62sYVERgN5f/
IbNYUWK0ii6jpoa8oYaCA1Y6vGufzkOXyOkkyyr/REW+8CnOgb8Nf/1H+aseCbAO
VPUbdenit3ut9RcnbbZqCU45kZEBqyOi97lNnUOcTSwVGYhUszONfSMgOjCFlWYh
9RknRejw/45hXQzoB6C4ZNXZfkU9bm5crkheIZnoO21nmQB1pJ4eWKIt3iz/yX9l
GW8KqwfaC0V5lAooewOQOf023XFcvAFI6RvxIdt4G/3GNt62Ve2f6PnLsx12hCf7
HV1XMbx7AgMBAAECggEAQsWuM529ueu9HDDI+o4y6YmaFln1/1H0PoxNm8OhdWX8
fb64nZjjJSlKXbfW97Sm7LMuTrgT8+KZSdiIQh8dH3EZReRiriQAMekKgk2Ra/oW
O2Mk2xO4Y12XSbccfMuUbSL96Dodu8qcZ+3o5WdqgZkVne/73Jnw9QmgwQ44eOUj
mlRi57jfxJqNUA+slEneI8stxfjgjVetObF0EXtwl+c74EgJamR/hhZXbXOlWa2o
aqbTlDnlTlQW45ETWwbYQLw40pp1HTQjL+ElBQIKukTkZXzOfG4FsGmBA108dUcE
urGXSIK46uHiWm6TKS+glOK0Xu/zz9Oa1I0Jbn+vQQKBgQDq0ub0wMsMSSjRuiWy
9tUZUSCQ84L0783AndAXS3XC/BBC1P3zM5ewPLowShxsyv53oZxpoOyf6BbRKGxp
k5FnCoVjtckF6W1i/cnc08jLcxEIvD4V0dJSpqB2/fYBKXiRkO2nShYE/xOLa6Hp
WZvXgbg+B6zM6umSeQDJuXf5nQKBgQDO/R3cUYLIXn10zlLcKithyuAQQF5NYF+n
dLKr/Tqqfu7lz66yx74c+OQqXFfzfVVfOW8wz1yt2MNuON2bR8sGp4vfq6w26GgD
eot+8+Ur06ez9ezKj76djw/0y+UKhMvmafvKBZGkYipVElR5aGzZYLVicfXvKMzZ
IKLGUJWe9wKBgQCvCWQ0npz73HC73EiLnSf9RhbDVXCRSUsSP9BD/PCb1i380y00
ool4SdvzcNq9UZba77FanySikWqon7wn+mKQ7yu8xl1Atd3ewxQ8MfVjibLx0vdo
Zk2jZCcKa4V7GkGQJ/quDzBYqxYTf7hh63SZ8Ey4mBn7aUOP9fhbZY+DlQKBgEHA
IcYkllizu0Jpb+TD+HfeDALdj5cgsAHvjfoYPJSAMb8Kk8HytS9a2I+kOcP84iuX
gPyOQjBvFNVkdvCmg5Wfj00DqXbfqHrCaKFxNDER0MnXqtpFgxVlpnnqct0+hc6x
h+wKjNMc47mWUwMl6r26fKPC845+9WNbfJlma8DNAoGBAMnE9Lz3O90s3gRYdZ98
SwbdRjvvcPL5QPDHaq4aTVcUKKuQOX/fgEuuNM46Aq2PI72SXSq51nb74GcjYvua
/azL7YXi6MULDqEEzlzIhuq4XcCSr3mPug4NxxXTI0f3uypJ4DS+PdpnAKUXh7HN
BnNKJ2ZXIu8x4cNM1hGUkmmz
-----END PRIVATE KEY-----'''
client_email = "solution-challenge@terminal-files.iam.gserviceaccount.com"
client_id = "100869033884134772566"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/solution-challenge%40terminal-files.iam.gserviceaccount.com"
